# tag current commit, that name is from pull request title
name: tag version
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  release:
    name: add version tag
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: add tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TAG: ${{github.event.pull_request.title}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: ./.github/scripts/add-tag.sh
