name: Timeout Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: sleep 75sec
        timeout-minutes: 1
        run: sleep 75
      # - name: try failure
      #   run: false
      - name: sleep 30sec
        run: sleep 30
      - name: check success
        if: success()
        run: echo "success"
      - name: check failure
        if: failure()
        run: echo "failure"
      - name: check cancelled
        if: cancelled()
        run: echo "cancelled"
      - name: check always
        if: always()
        run: echo "always"
      - name: check not if
        run: echo "not if"
