name: test workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      piyo:
        default: default strings
        description: test strings
        required: true
      fuga:
        default: default strings
        description: test strings
        required: true
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: target branch name
        uses: actions/github-script@v2
        id: set-target-branch
        with:
          result-encoding: string
          script: |
            console.log(context.ref);
            return 'dev'
      - name: test arguments
        run: echo "${{ steps.set-target-branch.outputs.result }}"
